### ISSUE TITLE
Bug: Object of type WindowsPath is not JSON serializable when running on Windows

### ISSUE THREAD

**Issue by AWS-Samuel** [aws-deadline/deadline-cloud-worker-agent#406]
### Describe Behaviour

When exiting a session action the following bug was observed:

```
[2024-08-29 22:29:24,927][INFO    ] 💾 FileSystem.Write 💾 Saving profile updates. [C:\ProgramData\Amazon\Deadline\Cache\queues\queue-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\config]
[2024-08-29 22:29:24,928][INFO    ] 💾 FileSystem.Write 💾 Saving profile updates. [C:\ProgramData\Amazon\Deadline\Cache\queues\queue-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\credentials]
[2024-08-29 22:29:24,929][ERROR   ] Exception in WorkerScheduler
Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\site-packages\deadline_worker_agent\scheduler\scheduler.py", line 291, in run
    interval = self._sync(interruptable=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\deadline_worker_agent\scheduler\scheduler.py", line 454, in _sync
    self._update_sessions(response=response)
  File "C:\Program Files\Python312\Lib\site-packages\deadline_worker_agent\scheduler\scheduler.py", line 612, in _update_sessions
    self._cleanup_queue_aws_credentials(assigned_sessions=assigned_sessions)
  File "C:\Program Files\Python312\Lib\site-packages\deadline_worker_agent\scheduler\scheduler.py", line 1211, in _cleanup_queue_aws_credentials
    credentials_dataclass.session.cleanup()
  File "C:\Program Files\Python312\Lib\site-packages\deadline_worker_agent\aws_credentials\queue_boto3_session.py", line 236, in cleanup
    self._delete_credentials_directory()
  File "C:\Program Files\Python312\Lib\site-packages\deadline_worker_agent\aws_credentials\queue_boto3_session.py", line 482, in _delete_credentials_directory
    _logger.warning(
  File "C:\Program Files\Python312\Lib\logging\__init__.py", line 1551, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "C:\Program Files\Python312\Lib\logging\__init__.py", line 1684, in _log
    self.handle(record)
  File "C:\Program Files\Python312\Lib\logging\__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "C:\Program Files\Python312\Lib\logging\__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "C:\Program Files\Python312\Lib\logging\__init__.py", line 1022, in handle
    rv = self.filter(record)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\logging\__init__.py", line 858, in filter
    result = f.filter(record)
             ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\deadline_worker_agent\log_messages.py", line 602, in filter
    record.json = json.dumps(structure, ensure_ascii=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WindowsPath is not JSON serializable
[2024-08-29 22:29:24,974][INFO    ] Main event loop exited.
[2024-08-29 22:29:24,974][INFO    ] Draining any remaining Sessions.
[2024-08-29 22:29:24,974][INFO    ] 🔑 AWSCreds.Delete 🔑 Uninstalling Credential Process. [queue-e47af62a55274932aa7ac2035c53bcd5][arn:aws:iam::xxxxxxxxxxxx:role/service-role/AWSDeadlineCloudQueueRole-xxxxxxxxxxxx]
[2024-08-29 22:29:24,974][ERROR   ] Object of type WindowsPath is not JSON serializable
[2024-08-29 22:29:24,974][ERROR   ] Worker Agent abnormal exit: Object of type WindowsPath is not JSON serializable
Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\site-packages\deadline_worker_agent\scheduler\scheduler.py", line 291, in run
    interval = self._sync(interruptable=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\deadline_worker_agent\scheduler\scheduler.py", line 454, in _sync
    self._update_sessions(response=response)
  File "C:\Program Files\Python312\Lib\site-packages\deadline_worker_agent\scheduler\scheduler.py", line 612, in _update_sessions
    self._cleanup_queue_aws_credentials(assigned_sessions=assigned_sessions)
  File "C:\Program Files\Python312\Lib\site-packages\deadline_worker_agent\scheduler\scheduler.py", line 1211, in _cleanup_queue_aws_credentials
    credentials_dataclass.session.cleanup()
  File "C:\Program Files\Python312\Lib\site-packages\deadline_worker_agent\aws_credentials\queue_boto3_session.py", line 236, in cleanup
    self._delete_credentials_directory()
  File "C:\Program Files\Python312\Lib\site-packages\deadline_worker_agent\aws_credentials\queue_boto3_session.py", line 482, in _delete_credentials_directory
    _logger.warning(
  File "C:\Program Files\Python312\Lib\logging\__init__.py", line 1551, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "C:\Program Files\Python312\Lib\logging\__init__.py", line 1684, in _log
    self.handle(record)
  File "C:\Program Files\Python312\Lib\logging\__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "C:\Program Files\Python312\Lib\logging\__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "C:\Program Files\Python312\Lib\logging\__init__.py", line 1022, in handle
    rv = self.filter(record)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\logging\__init__.py", line 858, in filter
    result = f.filter(record)
             ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\deadline_worker_agent\log_messages.py", line 602, in filter
    record.json = json.dumps(structure, ensure_ascii=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WindowsPath is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\site-packages\deadline_worker_agent\startup\entrypoint.py", line 173, in entrypoint
    worker_sessions.run()
  File "C:\Program Files\Python312\Lib\site-packages\deadline_worker_agent\worker.py", line 252, in run
    future.result()
  File "C:\Program Files\Python312\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Program Files\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\deadline_worker_agent\scheduler\scheduler.py", line 312, in run
    self._drain_scheduler()
  File "C:\Program Files\Python312\Lib\site-packages\deadline_worker_agent\scheduler\scheduler.py", line 373, in _drain_scheduler
    credentials_dataclass.session.cleanup()
  File "C:\Program Files\Python312\Lib\site-packages\deadline_worker_agent\aws_credentials\queue_boto3_session.py", line 236, in cleanup
    self._delete_credentials_directory()
  File "C:\Program Files\Python312\Lib\site-packages\deadline_worker_agent\aws_credentials\queue_boto3_session.py", line 482, in _delete_credentials_directory
    _logger.warning(
  File "C:\Program Files\Python312\Lib\logging\__init__.py", line 1551, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "C:\Program Files\Python312\Lib\logging\__init__.py", line 1684, in _log
    self.handle(record)
  File "C:\Program Files\Python312\Lib\logging\__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "C:\Program Files\Python312\Lib\logging\__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "C:\Program Files\Python312\Lib\logging\__init__.py", line 1022, in handle
    rv = self.filter(record)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\logging\__init__.py", line 858, in filter
    result = f.filter(record)
             ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\deadline_worker_agent\log_messages.py", line 602, in filter
    record.json = json.dumps(structure, ensure_ascii=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WindowsPath is not JSON serializable
[2024-08-29 22:29:25,283][CRITICAL] Object of type WindowsPath is not JSON serializable
[2024-08-29 22:29:25,283][INFO    ] 🚪 Worker Agent exiting
```

It appears as though the worker agent is trying to encode a `pathlib.WindowsPath` into a `JSON` object somewhere

### Reproduction Steps

This was the setup:

1. Queue which is configured to run jobs as the worker agent user (no Queue User configured)
2. Worker agent running as `Administrator` and started with `--run-job-as-agent-user`
3. Worker Agent `0.27.2` but including the patch in https://github.com/aws-deadline/deadline-cloud-worker-agent/pull/395
4. Failure occurred after exiting a job

### Package Version

`0.27.2`

### Language Version

3.12

### Operating System

Windows

**Comment by AWS-Samuel** [comment]
With #412 included in the latest worker agent release, we can now resolve this.
